### ISSUE TITLE
Patch for rbd support doesn't apply anymore

### ISSUE THREAD

**Issue by stormi** [xcp-ng-rpms/qemu-dp#5]
The Makefile changed in qemu 2.10.2 so the patch does not apply.

@rposudnevskiy if this `extras` version of qemu-dp is still needed for Ceph support, can you provide an updated patch?

**Comment by rposudnevskiy** [comment]
HI,
I have updated patches in the last commit [a4a8b06](https://github.com/xcp-ng-rpms/qemu-dp/pull/4/commits/a4a8b06d18ad6848cabb2ea9c1da65e8d74c79fa)

**Comment by stormi** [comment]
Thanks. I would have preferred a separate pull request, because I was waiting for your feedback on #4 before merging it, especially the part about submitting it to upstream QEMU. What's the status about that?

I'd still like improvements in https://github.com/xcp-ng/xcp/wiki/Ceph-on-XCP-ng-7.5-or-later because the current way the page is written does not allow to create a working setup.

And a last thing: in XS 7.6, the `xapi-storage-plugins` package, that uses `qemu-dp`, has been made Proprietary by Citrix. So XCP-ng 7.6 won't have this `xapi-storage-plugins` package, nor `sm-transport-lib` which is now proprietary also. Will Ceph still work with `qemu-dp` without those?

**Comment by stormi** [comment]
@rposudnevskiy I've seen your latest commit, it's good to have renamed the patches. Can you answer the questions from the above comment?

**Comment by rposudnevskiy** [comment]
Hi,
I have some issues with qemu-dp. The issues are related to glibc version. XS 7.5 and 7.6 use glibc-2.17-106. But there is an issue with this version, `xen-watch-device` qmp command doesn't work and this leads to the issue described here [#88](https://github.com/rposudnevskiy/RBDSR/issues/88). I use `https://github.com/xenserver/xenserver-build-env` to build XenServer packages. After installation of all requirements for qemu-dp I have glibc-2.17-222 in my build env (I think it because it gets latest glibc from centos repos). I have the same issue [#88](https://github.com/rposudnevskiy/RBDSR/issues/88) if use qemu-dp,  which was build using my build env, with glibc-2.17-106 of XenServer default installation, but it works fine if update glibc to 2.17-222. At the moment I am not sure where is the root of the problem. I don't know is it related to glibc-devel version with which I built qemu-dp or qemu-dp doesn't work with glibc-2.17-106 at all. I think it is a bad idea to update the default glibc version of XenServer. So this issue requires more investigation and this the reason I still not submitted my patches to upstream QEMU. Maybe the issue related to my patches, I don't know at the moment. What is the version of glibc in your build-env?

As for improvements in [https://github.com/xcp-ng/xcp/wiki/Ceph-on-XCP-ng-7.5-or-later](https://github.com/xcp-ng/xcp/wiki/Ceph-on-XCP-ng-7.5-or-later). I have made RBDSR.spec to build rpm package for RBDSR. I think we can put RBDSR rpm to `extras_testing` XCP-ng repo to allow just use yum install to enable RBD support in XCP-ng and I can write more detailed instruction on how to enable RBD in XCP-ng   

And the last thing: 
`xapi-storage-plugins` package provides `gfs2`, `nfs-ng` and `filebased` drivers for SMAPIv3. Also it provides `qemuback` daemon wich issues `xen-watch-device` qmp command to connect qemu-dp backend to xen domain and it also provides some useful python modules.
At the moment RBDSR uses some python modules from `xapi-storage-plugins` package and it also requires `qemuback` service. 
But I think it is not a big problem to write our own `qemuback` service and don't use modules from `xapi-storage-plugins` in RBDSR.

`qemu-dp` is not directly related to `xapi-storage-plugins`. It is just disk backend that is used by `xapi-storage-plugins` drivers.

**Comment by stormi** [comment]
Hi! We will release XCP-ng 7.6 very soon, so what should we do with qemu-dp? Juste merge the pull request and push the package as-is?

We can work on a RDBSR package in `extras_testing` after the release, if you have a version that is ready for XCP-ng 7.6 without any requirement on `xapi-storage-plugins`. Until then, it would be nice to update the wiki page and let it point at your RBDSR repository and instructions.

I've seen in https://github.com/rposudnevskiy/RBDSR/issues/88 that the newer glibc from CentOS fixes the issue. If you can identify the exact patch they applied to fix it, I'm willing to try patching XCP-ng's glibc package directly (`updates_testing` then `updates` once tested).

**Comment by stormi** [comment]
About the submission of patches to upstream `qemu`, now that the glibc-related issue is fixed, maybe you could do it?

**Comment by stormi** [comment]
Ping @rposudnevskiy 
We released XCP-ng 7.6 12 days ago but we still haven't your modified `qemu-dp` in the `extras_testing` repository. See my questions in above comments.

**Comment by stormi** [comment]
I've seen new commits to the pull request but I'm a bit lost about the maintenance of our qemu-dp package in the `extras` media.

XCP-ng 7.6 has been out for two months and we still haven't updated the `qemu-dp` package in it, which makes me consider simply dropping it. What do you think?

**Comment by darrynza** [comment]
bump ... seems as though this has died ? are we waiting  on XE 8 for support on clustered filesystems? As i see neither glusterfs or ceph are currently supported.

**Comment by olivierlambert** [comment]
Gluster works pretty well thanks to the open source driver (contributed through XOSAN). But yeah, SMAPIv3 will be a new start for all of them.

**Comment by darrynza** [comment]
is this documented ?

**Comment by olivierlambert** [comment]
Yes but it's not recommended except if you know what you are doing and that you are familiar with Gluster :)

https://github.com/xcp-ng/xcp/wiki/GlusterFS

**Comment by stormi** [comment]
Closing this for now. This does NOT mean that we're giving up on Ceph, but simply that the way that was contributed by @rposudnevskiy in XCP-ng 7.5 was not maintained since for various reasons (including the fact that some code was closed by Citrix). However, XCP-ng 8.0's kernel has a module for ceph support and once our developers have mastered the storage layer we will be able to consider doing it differently.

**Comment by stormi** [comment]
Note: I closed the bug report, but if there's a way to use RBDSR without the need for closed-source packages from Citrix, I'm all for reopening and checking what can be done. About including RBDSR as a RPM in XCP-ng repositories, I'm still open to consider it, but if we do include it, then we need some committment from @rposudnevskiy to maintain it whenever bugs are reported or new releases of XCP-ng are in development.
